name: Deploy microservice
on:
  # Deploy microservice on push to the main branch of this code repository.
  push: 
    branches:
      - master
  # Allow deployment to be invoked manually through the GitHub Actions user interface.
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

    steps:
      # Check-out repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3
      - name: Set script permissions
        run: chmod +x ./scripts/*.sh
      # Build Docker image.
      - name: Build
        run: ./scripts/build-image.sh
      # Publish Docker image to the container registry.
      - name: Publish
        run: ./scripts/push-image.sh
      # Decrypt Kubeconfig secret that is too large to store as secret
      - name: Decrypt large secret
        run: ./scripts/decrypt-secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
      # Read base64-encoded kubeconfig
      - name: Read Base64 Kubeconfig
        id: read-kubeconfig
        run: |
          base64_kubeconfig=$(cat $HOME/secrets/kubekubeconfig.txt)
          echo "::set-output name=base64_kubeconfig::$base64_kubeconfig"
      # Install Kubectl and connect to cluster.
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.24.2'
      - name: Set Kubeconfig
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ steps.read-kubeconfig.outputs.base64_kubeconfig }}
      # Expand configuration template and deploy microservice.
      - name: Deploy
        run: ./scripts/deploy.sh